Add free properties to line filter.
gridsuite/filter pull request #10
Opened 2024-04-09 12:23 UTC by AAJELLAL

2024-04-12 12:26 UTC, souissimai requested changes

2024-04-16 02:07 UTC, ayolab approved these changes

2024-04-18 07:21 UTC, AAJELLAL commented on src/main/java/org/gridsuite/filter/criteriafilter/AbstractLineFilter.java
> +                && MapUtils.isEmpty(freeProperties2)
I prefer keeping the old names at the moment. May be change it on a separate PR.

2024-04-18 14:01 UTC, souissimai approved these changes

2024-04-18 14:03 UTC, merged